[package]
name = "codexia"
version = "0.11.0"
description = "A powerful IDE/GUI and Toolkit for Codex CLI"
authors = ["milisp"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "codexia_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-log = "2"
tauri-plugin-screenshots = "2.2.0"
tauri-plugin-deep-link = "2"
tauri-plugin-process = "2"
tauri-remote-ui = { git = "https://github.com/DraviaVemal/tauri-remote-ui" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
anyhow = "1.0"
log = "0.4"
which = "6.0"
pdf-extract = "0.7.12"
csv = "1.3"
calamine = "0.25"
dirs = "6.0.0"
toml = "0.9.5"
toml_edit = "0.20"
walkdir = "2.3"
chrono = { version = "0.4", features = ["serde"] }
notify = "6"
codex-protocol = { git = "https://github.com/openai/codex.git", package = "codex-protocol" }
codex-app-server-protocol = { git = "https://github.com/openai/codex.git", package = "codex-app-server-protocol"}
base64 = "0.22.1"
nosleep = "0.2.1"
regex = "1.12.2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
tauri-plugin-updater = "2"

export_bindings = { path = "../export_bindings" }
